### ISSUE TITLE
mainブランチのプッシュでCIが回らないようにする

### ISSUE THREAD

**Issue by tsuna-can-se** [AlesInfiny/maris#1147]
# 概要

今の設定だと、ドキュメントのビルドとリリースのワークフローがmainブランチのプッシュでも動いてしまう。
ここはタグのプッシュと手動リリース実行時以外動く必要がない。

# 詳細 / 機能詳細（オプション）

以下の個所で branches を設定しているのが原因と思われる。
これを削除したい。

```yaml
on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+'
  workflow_dispatch:
```

# 完了条件

- mainブランチのプッシュ時にドキュメントリリースのワークフローが動作しないこと
