### ISSUE TITLE
actions/setup-dotnetがrollForwardの値を無視しなくなったら、CIパイプラインYAMLがglobal.jsonの値を参照するように修正する

### ISSUE THREAD

**Issue by kharada7** [AlesInfiny/maris#761]
## 2024/06/06 現在の調査
該当のPRがレビュー待ちのまま4/15から動きがない状態で、未解決。

### 概要

2024年1月25日時点で、actions/setup-dotnet は global.json に設定された rollForward の値を無視するようになっており、[これを修正するプルリクエスト](https://github.com/actions/setup-dotnet/pull/481) はまだマージされていない。
この挙動により、CIワークフロー内でインストールする .NET SDK のバージョンに差異が出てしまうようになったため、 #757 で暫定策として global.json を参照しないようにした。

[actions/setup-dotnet のプルリクエスト](https://github.com/actions/setup-dotnet/pull/481) がマージされたら、CI ワークフローが global.json を参照するよう設定を元に戻す。

### 詳細

対象は以下の2ファイル。

- `AlesInfiny\maris\.github\workflows\samples-dressca-backend.ci.yml`
- `AlesInfiny\maris\.github\workflows\samples-console-app-with-di.ci.yml`

.NET SDK のセットアップ部分を以下のように修正する。

```yaml
- name: .NET SDK のセットアップ
  uses: actions/setup-dotnet@v3
  with:
    global-json-file: [プロジェクト内のglobal.jsonファイル]
```

### 完了条件

- 「詳細」に示した2ファイルが各プロジェクトの global.json を参照するよう修正されていること。
